version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.populate
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      DATABASE_HOST: $DATABASE_HOST
    networks:
      - shared_network


networks:
  shared_network:
    external: true